name: Unit_Tests
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
jobs:
    test:
        run-on: ubuntu-latest
        steps:
            - name: setup
              uses: actions/checkout@v3
            - name: setup python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"
                  cache: "pip"
            - name: install dependencies
              run: |
                  python -m pip install --upgrade pip
                  cd backend
                  pip install -r requirements.pip
            - name: run unit test
              run: |
                  python -m pytest -m unit
